name: Generate new release (manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New Version (without leading v)"
        required: true
        type: string

jobs:
  generate-release:
    name: Generate new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git details
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: "scripts/release.py ${{ github.event.inputs.version }}"
